# Generated by Django 4.2.23 on 2025-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('pending', 'In afwachting'), ('approved', 'Goedgekeurd'), ('rejected', 'Afgekeurd')], db_index=True, default='pending', max_length=20),
        ),
    ]
