# /quote_project/docker-compose.yml

services:
  ### DATABASE SERVICE ###
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: myquoteproject_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d myquoteproject_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  ### DJANGO API SERVICE ###
  api:
    build:
      context: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: myquoteproject_db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  ### SVELTE FRONTEND SERVICE ###
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  

volumes:
  
  postgres_data: